dsv4-fp4-b300-vllm-agentic-memory-profile:
  image: cquil/vllm-openai:v0.22.1-dcc957098904749bf375ffbf85aba6c74dfc9fe9
  model: deepseek-ai/DeepSeek-V4-Pro
  model-prefix: dsv4
  runner: b300
  precision: fp4
  framework: vllm
  multinode: false
  scenarios:
    agentic-coding:
    - duration: 1800
      search-space:
      - { tp: 8, ep: 8, dp-attn: true, offloading: none, conc-list: [52, 64, 72, 84, 100, 128, 196, 256, 512] }
