kimik2.5-fp4-mi355x-vllm-disagg-mori-lmcache-agentic:
  image: yukiozzz/kimi-lmc-mc-rocm:dmabuf
  model: amd/Kimi-K2.5-MXFP4
  model-prefix: kimik2.5
  runner: mi355x-disagg
  precision: fp4
  framework: vllm-disagg
  multinode: true
  disagg: true
  scenarios:
    agentic-coding:
    - duration: 1800
      search-space:
      - spec-decoding: "none"
        offloading: lmcache-mp
        total-cpu-dram-gb: 1200
        conc-list: [ 16, 32, 48, 64 ]
        prefill:
          num-worker: 1
          tp: 8
          ep: 1
          dp-attn: false
          additional-settings:
          - "PREFILL_NODES=1"
          - "PREFILL_KV_CONNECTOR=moriio-lmcachemp"
        decode:
          num-worker: 1
          tp: 8
          ep: 1
          dp-attn: false
          additional-settings:
          - "DECODE_NODES=1"
          - "DECODE_KV_CONNECTOR=moriio"
