gptoss-fp4-b200-vllm-isb1-kv-stress:
  benchmark-type: isb1_kv_stress
  canonical-model-id: gpt_oss_120b
  framework: vllm
  hardware-profile-id: nvidia:b200_sxm_180gb
  image: vllm/vllm-openai:v0.15.1
  kv-cache-dtype: fp8
  kv-stress-configs:
  - export-file: datasets/isb1/exports/extension_131k/code_131k1k.json
    request-mode: multi-turn
    search-space:
    - duration-s: 1800
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    support-status: reviewed_preview
    tp-configs:
    - duration-s: 1800
      ep: 1
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      tp: 8
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    workload-type: code
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  precision: fp4
  runner: b200
  runtime-stack-id: standalone:vllm
gptoss-fp4-h100-vllm-isb1-kv-stress:
  benchmark-type: isb1_kv_stress
  canonical-model-id: gpt_oss_120b
  framework: vllm
  hardware-profile-id: nvidia:h100_sxm_80gb
  image: vllm/vllm-openai:v0.18.0
  kv-cache-dtype: fp8
  kv-stress-configs:
  - export-file: datasets/isb1/exports/extension_131k/code_131k1k.json
    request-mode: multi-turn
    search-space:
    - duration-s: 1800
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    support-status: reviewed_preview
    tp-configs:
    - duration-s: 1800
      ep: 1
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      tp: 8
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    workload-type: code
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  precision: fp4
  runner: h100
  runtime-stack-id: standalone:vllm
gptoss-fp4-h200-vllm-isb1-kv-stress:
  benchmark-type: isb1_kv_stress
  canonical-model-id: gpt_oss_120b
  framework: vllm
  hardware-profile-id: nvidia:h200_sxm_141gb
  image: vllm/vllm-openai:v0.18.0
  kv-cache-dtype: fp8
  kv-stress-configs:
  - export-file: datasets/isb1/exports/extension_131k/code_131k1k.json
    request-mode: multi-turn
    search-space:
    - duration-s: 1800
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    support-status: reviewed_preview
    tp-configs:
    - duration-s: 1800
      ep: 1
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      tp: 8
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    workload-type: code
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  precision: fp4
  runner: h200
  runtime-stack-id: standalone:vllm
minimaxm2.5-fp4-b200-vllm-isb1-kv-stress:
  benchmark-type: isb1_kv_stress
  canonical-model-id: minimax_m2_5
  framework: vllm
  hardware-profile-id: nvidia:b200_sxm_180gb
  image: vllm/vllm-openai:v0.19.0-cu130
  kv-cache-dtype: fp8
  kv-stress-configs:
  - export-file: datasets/isb1/exports/extension_131k/code_131k1k.json
    request-mode: multi-turn
    search-space:
    - duration-s: 1800
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    support-status: unsupported
    tp-configs:
    - duration-s: 1800
      ep: 1
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      tp: 8
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    workload-type: code
  model: nvidia/MiniMax-M2.5-NVFP4
  model-prefix: minimaxm2.5
  precision: fp4
  runner: b200
  runtime-stack-id: standalone:vllm
minimaxm2.5-fp8-b200-vllm-isb1-kv-stress:
  benchmark-type: isb1_kv_stress
  canonical-model-id: minimax_m2_5
  framework: vllm
  hardware-profile-id: nvidia:b200_sxm_180gb
  image: vllm/vllm-openai:v0.19.0-cu130
  kv-cache-dtype: fp8
  kv-stress-configs:
  - export-file: datasets/isb1/exports/extension_131k/code_131k1k.json
    request-mode: multi-turn
    search-space:
    - duration-s: 1800
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    support-status: unsupported
    tp-configs:
    - duration-s: 1800
      ep: 1
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      tp: 8
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    workload-type: code
  model: MiniMaxAI/MiniMax-M2.5
  model-prefix: minimaxm2.5
  precision: fp8
  runner: b200
  runtime-stack-id: standalone:vllm
minimaxm2.5-fp8-h100-vllm-isb1-kv-stress:
  benchmark-type: isb1_kv_stress
  canonical-model-id: minimax_m2_5
  framework: vllm
  hardware-profile-id: nvidia:h100_sxm_80gb
  image: vllm/vllm-openai:v0.18.0
  kv-cache-dtype: fp8
  kv-stress-configs:
  - export-file: datasets/isb1/exports/extension_131k/code_131k1k.json
    request-mode: multi-turn
    search-space:
    - duration-s: 1800
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    support-status: unsupported
    tp-configs:
    - duration-s: 1800
      ep: 1
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      tp: 8
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    workload-type: code
  model: MiniMaxAI/MiniMax-M2.5
  model-prefix: minimaxm2.5
  precision: fp8
  runner: h100
  runtime-stack-id: standalone:vllm
minimaxm2.5-fp8-h200-vllm-isb1-kv-stress:
  benchmark-type: isb1_kv_stress
  canonical-model-id: minimax_m2_5
  framework: vllm
  hardware-profile-id: nvidia:h200_sxm_141gb
  image: vllm/vllm-openai:v0.18.0
  kv-cache-dtype: fp8
  kv-stress-configs:
  - export-file: datasets/isb1/exports/extension_131k/code_131k1k.json
    request-mode: multi-turn
    search-space:
    - duration-s: 1800
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    support-status: unsupported
    tp-configs:
    - duration-s: 1800
      ep: 1
      offload-modes:
      - 'on'
      - 'off'
      - noprefix
      tp: 8
      users:
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
    workload-type: code
  model: MiniMaxAI/MiniMax-M2.5
  model-prefix: minimaxm2.5
  precision: fp8
  runner: h200
  runtime-stack-id: standalone:vllm
