minimaxm3-pr45567-fp8-mi355x-vllm:
  image: vllm/vllm-openai-rocm:minimax-m3
  model: MiniMaxAI/MiniMax-M3-MXFP8
  model-prefix: minimaxm3
  runner: mi355x
  precision: fp8
  framework: vllm
  multinode: false
  scenarios:
    fixed-seq-len:
    - isl: 1024
      osl: 1024
      search-space:
      - { tp: 8, conc-start: 4, conc-end: 4 }
      - { tp: 8, conc-start: 64, conc-end: 64 }
