minimaxm3-fp8-mi300x-vllm:
  image: vllm/vllm-openai-rocm:minimax-m3
  model: MiniMaxAI/MiniMax-M3-MXFP8
  model-prefix: minimaxm3
  runner: mi300x
  precision: fp8
  framework: vllm
  multinode: false
  scenarios:
    fixed-seq-len:
    - isl: 1024
      osl: 1024
      search-space:
      - { tp: 8, ep: 8, conc-start: 1, conc-end: 256 }
    - isl: 8192
      osl: 1024
      search-space:
      - { tp: 8, ep: 8, conc-start: 1, conc-end: 256 }
    - isl: 32768
      osl: 1024
      search-space:
      - { tp: 8, ep: 8, conc-start: 256, conc-end: 256 }
