# Temporary one-off tuning matrix. Do not add to perf-changelog.yaml.
minimaxm3-gb300-tune-frontends-v5:
  image: vllm/vllm-openai:minimax-m3-perf-arm64-13.0.1-7a67223
  model: MiniMaxAI/MiniMax-M3-MXFP8
  model-prefix: minimaxm3
  runner: gb300-nv
  precision: fp8
  framework: dynamo-vllm
  multinode: true
  disagg: true
  scenarios:
    fixed-seq-len:
    - isl: 8192
      osl: 1024
      search-space:
      - conc-list:
        - 6144
        prefill:
          num-worker: 12
          tp: 2
          ep: 2
          dp-attn: true
          additional-settings:
          - CONFIG_FILE=recipes/vllm/minimax-m3-gb300-fp8/tuning/8k1k/disagg-gb300-12p3d-dep2-dep8-multifrontend-12n.yaml
        decode:
          num-worker: 3
          tp: 8
          ep: 8
          dp-attn: true
