h200-fp8-llama70b:
  tp2:
    users: [2, 4, 6, 8, 10, 12, 16, 20, 24, 32]
    offload: ["on", "off"]
  tp4:
    users: [2, 4, 6, 8, 16, 24, 32, 40, 48, 56]
    offload: ["on", "off"]
  tp8:
    users: [2, 4, 6, 8, 16, 32, 48, 64, 80, 128, 256]
    offload: ["on", "off"]

mi355x-fp8-llama70b:
  tp2:
    users: [1, 2, 4, 8, 16, 24, 32, 40, 48, 56]
    offload: ["on", "off"]
  tp4:
    users: [1, 2, 4, 8, 16, 32, 48, 64, 80, 96, 112, 256]
    offload: ["on", "off"]
  tp8:
    users: [1, 2, 4, 8, 16, 32, 64, 96, 128, 160, 256, 512]
    offload: ["on", "off"]

h100-fp8-llama70b-lmcache:
  tp2:
    users: [1, 2, 4, 6, 8, 10, 12, 16, 20, 32, 64]
    offload: ["on", "off"]
  tp4:
    users: [1, 2, 4, 8, 12, 16, 20, 24, 32, 40, 64, 128]
    offload: ["on", "off"]
  tp8:
    users: [1, 2, 4, 8, 16, 24, 32, 48, 64, 128, 256]
    offload: ["on", "off"]

b200-fp4-dsr1:
  tp4:
    ep: 4
    users: [1, 2, 4, 8, 12, 16, 24, 32, 48, 64, 128]
    offload: ["on", "off"]
  tp8:
    ep: 8
    users: [1, 2, 4, 8, 12, 16, 32, 64, 128]
    offload: ["on", "off"]
