# SPDX-License-Identifier: GPL-3.0-only
"""Advanced system components and fan relationships."""

from power_model.models.advanced.components.base import (
    ComponentGroup,
    FixedPowerComponent,
    GenericComponent,
)
from power_model.models.advanced.components.fan import FanPower
from power_model.models.advanced.components.generic import (
    CPU,
    DDR5DIMM,
    X86CPU,
    FrontendDPU,
    NVMeDrive,
    PCIe4x16Retimer,
    PCIe5x16Retimer,
    PCIeSwitch,
    PEX89144PCIeSwitch,
    SwitchSide800GSR8Transceiver,
    SystemSide400GTransceiver,
    SystemSide800GTransceiver,
    SystemSideTransceiver,
)
from power_model.models.advanced.components.hgx_fans import (
    AffinityFanPower,
    HGXFanPolicy,
    NormalizedHGXFanPower,
)
from power_model.models.advanced.components.psu import (
    B200PSUEfficiency,
    B300PSUEfficiency,
    HopperPSUEfficiency,
    MI300PSUEfficiency,
    MI325PSUEfficiency,
    MI355PSUEfficiency,
    PSUEfficiencyModel,
    PSUEfficiencyPoint,
)
from power_model.models.advanced.components.ubb import (
    MI300UBB,
    MI325UBB,
    MI355UBB,
    AMD8WayUBB,
    B200HGXBoard,
    B300HGXBoard,
    BlackwellHGXNVSwitch,
    HopperHGXBoard,
    HopperHGXNVSwitch,
    NVIDIA8WayHGXBoard,
    UniversalBaseBoard,
)

__all__ = [
    "AffinityFanPower",
    "HGXFanPolicy",
    "NormalizedHGXFanPower",
    "PSUEfficiencyModel",
    "PSUEfficiencyPoint",
    "HopperPSUEfficiency",
    "B200PSUEfficiency",
    "B300PSUEfficiency",
    "MI300PSUEfficiency",
    "MI325PSUEfficiency",
    "MI355PSUEfficiency",
    "AMD8WayUBB",
    "B200HGXBoard",
    "B300HGXBoard",
    "BlackwellHGXNVSwitch",
    "CPU",
    "ComponentGroup",
    "DDR5DIMM",
    "FanPower",
    "FixedPowerComponent",
    "FrontendDPU",
    "GenericComponent",
    "HopperHGXBoard",
    "HopperHGXNVSwitch",
    "MI300UBB",
    "MI325UBB",
    "MI355UBB",
    "NVMeDrive",
    "NVIDIA8WayHGXBoard",
    "PEX89144PCIeSwitch",
    "PCIe4x16Retimer",
    "PCIe5x16Retimer",
    "PCIeSwitch",
    "SystemSide400GTransceiver",
    "SwitchSide800GSR8Transceiver",
    "SystemSide800GTransceiver",
    "SystemSideTransceiver",
    "UniversalBaseBoard",
    "X86CPU",
]
