kimik2.5-fp4-mi355x-vllm-disagg-mori-lmcache-agentic:
  image: yukiozzz/kimi-lmc-mc-rocm:dmabuf
  model: amd/Kimi-K2.5-MXFP4
  model-prefix: kimik2.5
  runner: cluster:mi355x-amds
  precision: fp4
  framework: vllm-disagg
  multinode: true
  disagg: true
  scenarios:
    agentic-coding:
    - search-space:
      - spec-decoding: "none"
        kv-offloading: dram
        kv-offload-backend: lmcache
        total-cpu-dram-gb: 1200
        conc-list: [ 16, 32, 48, 64 ]
        prefill:
          num-worker: 1
          tp: 8
          ep: 1
          dp-attn: false
          additional-settings:
          - "PREFILL_NODES=1"
          - "PREFILL_KV_CONNECTOR=moriio-lmcachemp"
          - "LMCACHE_L1_SIZE_GB=1200"
        decode:
          num-worker: 2
          tp: 8
          ep: 1
          dp-attn: false
          additional-settings:
          - "DECODE_NODES=2"
          - "DECODE_KV_CONNECTOR=moriio"

kimik2.7-code-fp4-mi355x-vllm-disagg-mori-lmcache-agentic:
  image: yukiozzz/kimi-lmc-mc-rocm:dmabuf
  model: amd/Kimi-K2.7-Code-MXFP4
  model-prefix: kimik2.7-code
  runner: cluster:mi355x-amds
  precision: fp4
  framework: vllm-disagg
  multinode: true
  disagg: true
  scenarios:
    agentic-coding:
    - search-space:
      - spec-decoding: "none"
        kv-offloading: dram
        kv-offload-backend: lmcache
        total-cpu-dram-gb: 2000
        conc-list: [ 16, 32, 48, 64 ]
        prefill:
          num-worker: 1
          tp: 8
          ep: 1
          dp-attn: false
          additional-settings:
          - "PREFILL_NODES=1"
          - "PREFILL_KV_CONNECTOR=moriio-lmcachemp"
          - "LMCACHE_L1_SIZE_GB=2000"
        decode:
          num-worker: 2
          tp: 8
          ep: 1
          dp-attn: false
          additional-settings:
          - "DECODE_NODES=2"
          - "DECODE_KV_CONNECTOR=moriio"
