dsv4-fp4-mi355x-vllm-agentic-mtp-dpatp-nightly:
  image: vllm/vllm-openai-rocm:nightly-eed1f3d0c6043bd494424a22443ee198dd56f657
  model: deepseek-ai/DeepSeek-V4-Pro
  model-prefix: dsv4
  runner: cluster:mi355x-amds
  precision: fp4
  framework: vllm
  multinode: false
  scenarios:
    agentic-coding:
    - dram-utilization: 0.60
      search-space:
      - { tp: 8, ep: 1, dp-attn: true, kv-offloading: none, spec-decoding: mtp, conc-list: [64, 128, 256], router: { name: vllm-router, version: "0.1.14" } }
