qwen3.5-fp8-b300-sglang-agentic-mtp:
  image: lmsysorg/sglang:nightly-dev-cu13-20260914-4358a161
  model: Qwen/Qwen3.5-397B-A17B-FP8
  model-prefix: qwen3.5
  runner: cluster:b300-dsxe
  precision: fp8
  framework: sglang
  multinode: false
  scenarios:
    agentic-coding:
    - dram-utilization: 0.8
      search-space:
      - tp: 4
        ep: 1
        spec-decoding: mtp
        kv-offloading: none
        conc-list:
        - 1
        - 32
      - tp: 2
        ep: 2
        spec-decoding: mtp
        kv-offloading: none
        conc-list:
        - 32
      - tp: 2
        ep: 2
        spec-decoding: mtp
        kv-offloading: dram
        kv-offload-backend:
          name: hicache
        conc-list:
        - 32
