qwen3.5-fp4-b300-sglang-agentic-mtp-debug:
  image: lmsysorg/sglang:v0.5.16-cu130
  model: nvidia/Qwen3.5-397B-A17B-NVFP4
  model-prefix: qwen3.5
  runner: cluster:b300-nv
  precision: fp4
  framework: sglang
  multinode: false
  scenarios:
    agentic-coding:
    - dram-utilization: 0.80
      search-space:
      - { tp: 2, ep: 2, spec-decoding: mtp, kv-offloading: dram, kv-offload-backend: { name: hicache }, conc-list: [32, 34] }
