"""List the config keys whose benchmark points differ from a base revision.

A point is a recipe fingerprint at one concurrency. Results collected at the base cover a key
only while its points are unchanged, so the listed keys are the ones a perf-changelog entry
would rerun. The base generates its matrix with its own generator; both sides are fingerprinted
with this checkout's rule, each under its own recipes.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
from collections.abc import Iterable
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

import yaml

from infx.config import MASTER_CONFIGS, RUNNER_CONFIG

from .fingerprint import recipe_fingerprint
from .generate import generate_config_matrix
from .revision import snapshot
from .validation import config_root, load_config_files, load_runner_file

# Each key's points by (fingerprint, concurrency), and why any of its rows has no fingerprint.
Matrix = dict[str, tuple[dict[tuple[str | None, int], dict[str, Any]], list[str]]]


def _points(rows: list[dict], root: Path) -> tuple[dict, list[str]]:
    points, errors = {}, []
    for row in rows:
        try:
            fingerprint = recipe_fingerprint(row, root)
        except ValueError as error:
            fingerprint = None
            errors.append(str(error))
        for conc in row["conc"] if isinstance(row["conc"], list) else [row["conc"]]:
            points[fingerprint, conc] = {**row, "conc": conc, "recipe-fingerprint": fingerprint}
    return points, errors


def head_matrix(config_files: list[str], runner_config: str) -> Matrix:
    master = load_config_files(config_files)
    runners = load_runner_file(runner_config)
    root = config_root(config_files)
    return {
        key: _points(
            generate_config_matrix([key], master, runners, eval_mode="none", root=root), root
        )
        for key in master
    }


def base_matrix(ref: str, config_files: list[str]) -> Matrix:
    """``ref``'s points, each key generated by its own generator from a one-key config copy."""
    with snapshot(ref) as revision:
        configs = Path(revision.runner_config).parent
        files = [configs / Path(path).name for path in config_files]
        master = load_config_files([str(path) for path in files if path.is_file()], validate=False)
        singles = []
        for index, (key, entry) in enumerate(master.items()):
            # Validating every entry per key would dominate the run.
            single = configs / f"changed-{index}.yaml"
            single.write_text(yaml.safe_dump({key: entry}, sort_keys=False))
            singles.append(str(single))

        def generate(key: str, single: str) -> list[dict]:
            return revision.generate([key], ["--no-evals"], [single])

        with ThreadPoolExecutor(os.cpu_count()) as pool:
            rows = list(pool.map(generate, master, singles))
        return {
            key: _points(generated, revision.root)
            for key, generated in zip(master, rows, strict=True)
        }


def _sorted(points: Iterable[dict]) -> list[dict]:
    return sorted(points, key=lambda point: (str(point.get("exp-name")), point["conc"]))


def _keys(base: Matrix, head: Matrix) -> list[str]:
    return [*head, *(key for key in base if key not in head)]


def compare(base: Matrix, head: Matrix) -> list[dict]:
    """Each key whose points differ, with its point counts and added and removed points."""
    changed = []
    for key in _keys(base, head):
        before, after = base.get(key, ({}, []))[0], head.get(key, ({}, []))[0]
        added = _sorted(after[point] for point in after.keys() - before.keys())
        removed = _sorted(before[point] for point in before.keys() - after.keys())
        if added or removed:
            changed.append(
                {
                    "config-key": key,
                    "base-points": len(before),
                    "head-points": len(after),
                    "added": added,
                    "removed": removed,
                }
            )
    return changed


def _label(point: dict) -> str:
    if "prefill" in point:
        shape = str(point.get("srt-recipe", "")).rpartition("/")[2]
    else:
        shape = f"tp{point['tp']} ep{point['ep']}"
    fingerprint = point["recipe-fingerprint"]
    recipe = fingerprint[:12] if fingerprint else "no fingerprint"
    return f"{point.get('exp-name')} {shape} conc {point['conc']} {recipe}"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="List config keys whose benchmark points or recipes differ from a base."
    )
    parser.add_argument("--base", required=True, help="Git ref to compare with, e.g. origin/main")
    parser.add_argument("--config-files", nargs="+", default=MASTER_CONFIGS)
    parser.add_argument("--runner-config", default=RUNNER_CONFIG)
    parser.add_argument("--json", action="store_true", help="print the report as JSON")
    args = parser.parse_args(argv)
    head = head_matrix(args.config_files, args.runner_config)
    try:
        base = base_matrix(args.base, args.config_files)
    except subprocess.CalledProcessError as error:
        parser.exit(1, f"{args.base} could not generate its matrix:\n{error.stderr}")
    changed = compare(base, head)
    keys = _keys(base, head)
    if args.json:
        errors = [
            {"config-key": key, "revision": revision, "error": message}
            for revision, matrix in (("base", base), ("head", head))
            for key, (_, messages) in matrix.items()
            for message in messages
        ]
        report = {"base": args.base, "config-keys": len(keys), "changed": changed, "errors": errors}
        print(json.dumps(report, indent=2))
        return
    for change in changed:
        print(
            f"{change['config-key']}: {change['base-points']} -> {change['head-points']} points, "
            f"{len(change['added'])} added, {len(change['removed'])} removed"
        )
        for sign, points in (("+", change["added"]), ("-", change["removed"])):
            print("".join(f"  {sign} {_label(point)}\n" for point in points), end="")
    print(f"{len(changed)} of {len(keys)} config keys changed since {args.base}.")
    # Planning a row without a fingerprint fails; --json carries every message in full.
    for key in keys:
        current, previous = head.get(key, ({}, []))[1], base.get(key, ({}, []))[1]
        if current:
            print(f"warning: {len(current)} rows of {key} have no fingerprint: {current[0][:300]}")
        if previous and previous != current:
            print(
                f"warning: {len(previous)} rows of {key} have no fingerprint at {args.base}: "
                f"{previous[0][:300]}"
            )


if __name__ == "__main__":
    main()
