#!/usr/bin/bash

set -x

echo "Cloning srt-slurm-trtllm repository..."
TRTLLM_REPO_DIR="srt-slurm-trtllm"
if [ -d "$TRTLLM_REPO_DIR" ]; then
    echo "Removing existing $TRTLLM_REPO_DIR..."
    rm -rf "$TRTLLM_REPO_DIR"
fi

git clone https://github.com/jthomson04/srt-slurm-trtllm.git "$TRTLLM_REPO_DIR"
cd "$TRTLLM_REPO_DIR"
git checkout jthomson04/trtllm-support

echo "Installing srtctl..."
pip install -e .

cd "$GITHUB_WORKSPACE"

if ! command -v srtctl &> /dev/null; then
    echo "Error: Failed to install srtctl"
    exit 1
fi

echo "Configs available at: $TRTLLM_REPO_DIR/"

export HF_HUB_CACHE_MOUNT="/scratch/fsw/hf_hub_cache/"
export PORT_OFFSET=0

MODEL_CODE="${EXP_NAME%%_*}"

if [[ $MODEL_PREFIX == "gptoss" ]]; then
    export MODEL_PATH="/scratch/fsw/models/gpt-oss-120b"
    export SERVED_MODEL_NAME="openai/gpt-oss-120b"
elif [[ $MODEL_PREFIX == "dsr1" ]]; then
    export MODEL_PATH="/scratch/fsw/models/deepseek-r1-0528"
    export SERVED_MODEL_NAME="deepseek-ai/DeepSeek-R1-0528"
else
    echo "Unsupported model prefix: $MODEL_PREFIX. Supported prefixes are: gptoss, dsr1"
    exit 1
fi

export SLURM_PARTITION="${SLURM_PARTITION:-gpu}"
export SLURM_ACCOUNT="${SLURM_ACCOUNT:-default}"

export ISL="$ISL"
export OSL="$OSL"

# Create srtslurm.yaml for srtctl
echo "Creating srtslurm.yaml configuration..."
cat > srtslurm.yaml <<EOF
# SRT SLURM Configuration for H200
# Auto-generated by launch_h200-srtslurm.sh

# Default SLURM settings
default_account: "${SLURM_ACCOUNT}"
default_partition: "${SLURM_PARTITION}"
default_time_limit: "4:00:00"

# Resource defaults
gpus_per_node: 8
network_interface: ""

# Path to srtctl repo root (where the production configs live)
srtctl_root: "${GITHUB_WORKSPACE}/srt-slurm-trtllm"

# Model path aliases
model_paths:
  "${MODEL_PREFIX}": "${MODEL_PATH}"
EOF

echo "Generated srtslurm.yaml:"
cat srtslurm.yaml

bash benchmarks/"${MODEL_CODE}_${PRECISION}_h200_${FRAMEWORK}_slurm.sh"

# Wait for all jobs to complete
echo "Waiting for all jobs to complete..."
while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
    echo "Jobs still running..."
    squeue --steps -u $USER
    sleep 30
done

echo "Collecting results..."

# Find the logs directory created by srtctl
# srtctl creates logs in logs/<job_id>_*P_*D_*/
LOGS_DIR=$(find logs -maxdepth 1 -type d -name "*_*P_*D_*" -printf '%T@ %p\n' | sort -n | tail -1 | cut -d' ' -f2-)

if [ -z "$LOGS_DIR" ]; then
    echo "Warning: No srtctl logs directory found"
    exit 1
fi

echo "Found logs directory: $LOGS_DIR"

if [ -d "$LOGS_DIR/results" ]; then
    echo "Processing results from: $LOGS_DIR/results"
    
    for result_file in "$LOGS_DIR/results"/*.json; do
        if [ -f "$result_file" ]; then
            filename=$(basename "$result_file")
            WORKSPACE_RESULT_FILE="$GITHUB_WORKSPACE/${RESULT_FILENAME}_${filename}"
            cp "$result_file" "$WORKSPACE_RESULT_FILE"
            echo "Copied result: $result_file -> $WORKSPACE_RESULT_FILE"
        fi
    done
else
    echo "Warning: Results directory not found at $LOGS_DIR/results"
fi

echo "All result files processed"

